import { Employee } from "../services/employee.service";

export const EMPLOYEES: Employee[] = [
  {
    username: "gnecrews0",
    firstName: "Gabrielle",
    lastName: "Necrews",
    email: "gnecrews0@example.com",
    birthDate: "1986-05-22",
    basicSalary: 35578486.65,
    status: "Permanent",
    group: "Support",
    description:
      "est congue elementum in hac habitasse platea dictumst morbi vestibulum",
  },
  {
    username: "sspalton1",
    firstName: "Schuyler",
    lastName: "Spalton",
    email: "sspalton1@example.com",
    birthDate: "1972-04-28",
    basicSalary: 28200491.3,
    status: "Contract",
    group: "Accounting",
    description: "etiam pretium iaculis justo in hac habitasse platea dictumst",
  },
  {
    username: "athick2",
    firstName: "Annadiana",
    lastName: "Thick",
    email: "athick2@example.com",
    birthDate: "1978-12-25",
    basicSalary: 37725033.86,
    status: "Permanent",
    group: "Legal",
    description: "cursus id turpis integer aliquet massa id lobortis",
  },
  {
    username: "aworkes3",
    firstName: "Allene",
    lastName: "Workes",
    email: "aworkes3@example.com",
    birthDate: "1982-03-08",
    basicSalary: 24927611.85,
    status: "Permanent",
    group: "Services",
    description:
      "libero nullam sit amet turpis elementum ligula vehicula consequat morbi",
  },
  {
    username: "cdeakes4",
    firstName: "Cory",
    lastName: "Deakes",
    email: "cdeakes4@example.com",
    birthDate: "1984-08-24",
    basicSalary: 7366937.0,
    status: "Contract",
    group: "Engineering",
    description: "lorem id ligula suspendisse ornare consequat lectus in est",
  },
  {
    username: "bpedgrift5",
    firstName: "Binny",
    lastName: "Pedgrift",
    email: "bpedgrift5@example.com",
    birthDate: "1997-12-24",
    basicSalary: 48822873.17,
    status: "Permanent",
    group: "Research and Development",
    description: "ultrices vel augue vestibulum ante ipsum",
  },
  {
    username: "ztwydell6",
    firstName: "Zora",
    lastName: "Twydell",
    email: "ztwydell6@example.com",
    birthDate: "1987-05-20",
    basicSalary: 35226270.58,
    status: "Permanent",
    group: "Research and Development",
    description: "commodo vulputate justo in blandit ultrices enim",
  },
  {
    username: "sdutnall7",
    firstName: "Stan",
    lastName: "Dutnall",
    email: "sdutnall7@example.com",
    birthDate: "1972-03-03",
    basicSalary: 25526679.05,
    status: "Contract",
    group: "Product Management",
    description:
      "in tempor turpis nec euismod scelerisque quam turpis adipiscing",
  },
  {
    username: "agoney8",
    firstName: "Alma",
    lastName: "Goney",
    email: "agoney8@example.com",
    birthDate: "1965-05-06",
    basicSalary: 47677135.75,
    status: "Permanent",
    group: "Support",
    description: "duis mattis egestas metus aenean fermentum",
  },
  {
    username: "nodea9",
    firstName: "Nichols",
    lastName: "O'Dea",
    email: "nodea9@example.com",
    birthDate: "1973-08-23",
    basicSalary: 6921549.0,
    status: "Contract",
    group: "Accounting",
    description: "tempus semper est quam pharetra magna ac",
  },
  {
    username: "ddruitta",
    firstName: "Darb",
    lastName: "Druitt",
    email: "ddruitta@example.com",
    birthDate: "1993-01-18",
    basicSalary: 46090874.69,
    status: "Contract",
    group: "Marketing",
    description: "neque aenean auctor gravida sem praesent id massa",
  },
  {
    username: "ttollandb",
    firstName: "Teador",
    lastName: "Tolland",
    email: "ttollandb@example.com",
    birthDate: "1988-12-12",
    basicSalary: 27578745.77,
    status: "Contract",
    group: "Legal",
    description: "varius nulla facilisi cras non velit nec nisi",
  },
  {
    username: "asimoninic",
    firstName: "Aubrette",
    lastName: "Simonini",
    email: "asimoninic@example.com",
    birthDate: "1991-03-30",
    basicSalary: 33945480.12,
    status: "Permanent",
    group: "Research and Development",
    description: "pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis",
  },
  {
    username: "jstreatherd",
    firstName: "Jerrome",
    lastName: "Streather",
    email: "jstreatherd@example.com",
    birthDate: "1969-11-08",
    basicSalary: 36820212.6,
    status: "Contract",
    group: "Engineering",
    description: "mi pede malesuada in imperdiet et",
  },
  {
    username: "mdellite",
    firstName: "Maxi",
    lastName: "Dellit",
    email: "mdellite@example.com",
    birthDate: "1975-12-14",
    basicSalary: 41078360.38,
    status: "Permanent",
    group: "Support",
    description: "velit vivamus vel nulla eget eros",
  },
  {
    username: "texeterf",
    firstName: "Tally",
    lastName: "Exeter",
    email: "texeterf@example.com",
    birthDate: "1967-10-15",
    basicSalary: 18551190.9,
    status: "Contract",
    group: "Product Management",
    description: "integer pede justo lacinia eget tincidunt",
  },
  {
    username: "njuddg",
    firstName: "Nata",
    lastName: "Judd",
    email: "njuddg@example.com",
    birthDate: "1970-05-31",
    basicSalary: 25524238.69,
    status: "Permanent",
    group: "Accounting",
    description: "ac neque duis bibendum morbi",
  },
  {
    username: "jkemmeyh",
    firstName: "Jocko",
    lastName: "Kemmey",
    email: "jkemmeyh@example.com",
    birthDate: "1969-03-28",
    basicSalary: 8332262.0,
    status: "Contract",
    group: "Legal",
    description: "congue elementum in hac habitasse platea",
  },
  {
    username: "mstarcksi",
    firstName: "Madelyn",
    lastName: "Starcks",
    email: "mstarcksi@example.com",
    birthDate: "1974-08-14",
    basicSalary: 39342439.79,
    status: "Permanent",
    group: "Accounting",
    description: "a libero nam dui proin leo odio porttitor",
  },
  {
    username: "dquickendenj",
    firstName: "Deeanne",
    lastName: "Quickenden",
    email: "dquickendenj@example.com",
    birthDate: "1965-08-26",
    basicSalary: 46459784.2,
    status: "Permanent",
    group: "Services",
    description:
      "convallis duis consequat dui nec nisi volutpat eleifend donec ut",
  },
  {
    username: "ttuohyk",
    firstName: "Tomas",
    lastName: "Tuohy",
    email: "ttuohyk@example.com",
    birthDate: "1966-04-16",
    basicSalary: 38044930.59,
    status: "Contract",
    group: "Research and Development",
    description: "volutpat convallis morbi odio odio",
  },
  {
    username: "jbrandolinil",
    firstName: "Jenelle",
    lastName: "Brandolini",
    email: "jbrandolinil@example.com",
    birthDate: "1978-03-10",
    basicSalary: 31742367.7,
    status: "Permanent",
    group: "Product Management",
    description: "eget congue eget semper rutrum nulla nunc",
  },
  {
    username: "fschulem",
    firstName: "Floris",
    lastName: "Schule",
    email: "fschulem@example.com",
    birthDate: "1973-08-31",
    basicSalary: 7875857.69,
    status: "Permanent",
    group: "Training",
    description:
      "vulputate elementum nullam varius nulla facilisi cras non velit nec",
  },
  {
    username: "rriversn",
    firstName: "Robina",
    lastName: "Rivers",
    email: "rriversn@example.com",
    birthDate: "1991-05-24",
    basicSalary: 47310137.99,
    status: "Permanent",
    group: "Services",
    description: "quam turpis adipiscing lorem vitae mattis nibh ligula nec",
  },
  {
    username: "agillesono",
    firstName: "Anabelle",
    lastName: "Gilleson",
    email: "agillesono@example.com",
    birthDate: "1979-11-04",
    basicSalary: 39886428.77,
    status: "Permanent",
    group: "Marketing",
    description: "in leo maecenas pulvinar lobortis est phasellus sit",
  },
  {
    username: "crowcliffep",
    firstName: "Chantalle",
    lastName: "Rowcliffe",
    email: "crowcliffep@example.com",
    birthDate: "1986-11-02",
    basicSalary: 23164872.79,
    status: "Permanent",
    group: "Product Management",
    description: "auctor gravida sem praesent id massa",
  },
  {
    username: "hdickyq",
    firstName: "Henrietta",
    lastName: "Dicky",
    email: "hdickyq@example.com",
    birthDate: "1971-08-19",
    basicSalary: 36721112.67,
    status: "Permanent",
    group: "Legal",
    description: "est risus auctor sed tristique in tempus sit amet sem",
  },
  {
    username: "mbearcroftr",
    firstName: "Melitta",
    lastName: "Bearcroft",
    email: "mbearcroftr@example.com",
    birthDate: "1986-02-26",
    basicSalary: 49992133.92,
    status: "Permanent",
    group: "Sales",
    description: "primis in faucibus orci luctus et ultrices",
  },
  {
    username: "khadigates",
    firstName: "Kristofor",
    lastName: "Hadigate",
    email: "khadigates@example.com",
    birthDate: "1995-12-18",
    basicSalary: 38304036.46,
    status: "Contract",
    group: "Engineering",
    description:
      "amet consectetuer adipiscing elit proin risus praesent lectus",
  },
  {
    username: "cstoutet",
    firstName: "Chrisy",
    lastName: "Stoute",
    email: "cstoutet@example.com",
    birthDate: "1977-12-11",
    basicSalary: 8447222.0,
    status: "Contract",
    group: "Human Resources",
    description: "dui nec nisi volutpat eleifend donec ut dolor",
  },
  {
    username: "eelfittu",
    firstName: "Eugine",
    lastName: "Elfitt",
    email: "eelfittu@example.com",
    birthDate: "1973-02-02",
    basicSalary: 14081273.13,
    status: "Permanent",
    group: "Research and Development",
    description: "potenti nullam porttitor lacus at turpis",
  },
  {
    username: "ileverichv",
    firstName: "Inger",
    lastName: "Leverich",
    email: "ileverichv@example.com",
    birthDate: "1994-12-07",
    basicSalary: 46661398.18,
    status: "Permanent",
    group: "Marketing",
    description: "sed vestibulum sit amet cursus id turpis",
  },
  {
    username: "gjandlw",
    firstName: "Grata",
    lastName: "Jandl",
    email: "gjandlw@example.com",
    birthDate: "1969-05-30",
    basicSalary: 6202132.94,
    status: "Permanent",
    group: "Human Resources",
    description: "sagittis nam congue risus semper",
  },
  {
    username: "tbilbeex",
    firstName: "Tamiko",
    lastName: "Bilbee",
    email: "tbilbeex@example.com",
    birthDate: "1966-04-27",
    basicSalary: 28180633.4,
    status: "Permanent",
    group: "Research and Development",
    description: "nulla tempus vivamus in felis",
  },
  {
    username: "rcromey",
    firstName: "Rog",
    lastName: "Crome",
    email: "rcromey@example.com",
    birthDate: "1983-12-15",
    basicSalary: 41925949.35,
    status: "Contract",
    group: "Product Management",
    description: "faucibus orci luctus et ultrices",
  },
  {
    username: "ggraftonherbertz",
    firstName: "Greggory",
    lastName: "Grafton-Herbert",
    email: "ggraftonherbertz@example.com",
    birthDate: "1977-06-14",
    basicSalary: 5122998.13,
    status: "Contract",
    group: "Marketing",
    description: "pharetra magna ac consequat metus sapien ut nunc vestibulum",
  },
  {
    username: "gchittenden10",
    firstName: "Gray",
    lastName: "Chittenden",
    email: "gchittenden10@example.com",
    birthDate: "1972-09-28",
    basicSalary: 42311345.22,
    status: "Permanent",
    group: "Support",
    description: "ac est lacinia nisi venenatis tristique fusce congue diam",
  },
  {
    username: "sharome11",
    firstName: "Shina",
    lastName: "Harome",
    email: "sharome11@example.com",
    birthDate: "1984-04-13",
    basicSalary: 30780561.3,
    status: "Permanent",
    group: "Legal",
    description: "odio cras mi pede malesuada",
  },
  {
    username: "vflecknoe12",
    firstName: "Vera",
    lastName: "Flecknoe",
    email: "vflecknoe12@example.com",
    birthDate: "1962-09-08",
    basicSalary: 46645078.26,
    status: "Permanent",
    group: "Support",
    description: "nunc proin at turpis a pede posuere nonummy integer",
  },
  {
    username: "araymen13",
    firstName: "Arlen",
    lastName: "Raymen",
    email: "araymen13@example.com",
    birthDate: "1981-04-30",
    basicSalary: 15606722.27,
    status: "Contract",
    group: "Engineering",
    description: "felis ut at dolor quis odio consequat",
  },
  {
    username: "ftabord14",
    firstName: "Fairleigh",
    lastName: "Tabord",
    email: "ftabord14@example.com",
    birthDate: "1983-01-17",
    basicSalary: 17625698.7,
    status: "Contract",
    group: "Legal",
    description: "sit amet nulla quisque arcu libero rutrum ac",
  },
  {
    username: "xnassau15",
    firstName: "Xenia",
    lastName: "Nassau",
    email: "xnassau15@example.com",
    birthDate: "1962-08-03",
    basicSalary: 47314701.61,
    status: "Permanent",
    group: "Human Resources",
    description:
      "consectetuer adipiscing elit proin interdum mauris non ligula pellentesque",
  },
  {
    username: "jurwin16",
    firstName: "Janelle",
    lastName: "Urwin",
    email: "jurwin16@example.com",
    birthDate: "1999-09-06",
    basicSalary: 25390332.24,
    status: "Permanent",
    group: "Legal",
    description: "vitae consectetuer eget rutrum at lorem integer",
  },
  {
    username: "obrittoner17",
    firstName: "Odo",
    lastName: "Brittoner",
    email: "obrittoner17@example.com",
    birthDate: "1980-01-21",
    basicSalary: 33553468.68,
    status: "Contract",
    group: "Business Development",
    description: "aliquet at feugiat non pretium quis",
  },
  {
    username: "cleverentz18",
    firstName: "Caleb",
    lastName: "Leverentz",
    email: "cleverentz18@example.com",
    birthDate: "1993-05-30",
    basicSalary: 10736112.92,
    status: "Contract",
    group: "Marketing",
    description: "sapien sapien non mi integer ac neque",
  },
  {
    username: "mdormer19",
    firstName: "Mikol",
    lastName: "Dormer",
    email: "mdormer19@example.com",
    birthDate: "1965-09-19",
    basicSalary: 33132171.32,
    status: "Contract",
    group: "Accounting",
    description: "lobortis sapien sapien non mi integer ac",
  },
  {
    username: "dwitherbed1a",
    firstName: "Dara",
    lastName: "Witherbed",
    email: "dwitherbed1a@example.com",
    birthDate: "1996-04-10",
    basicSalary: 7552901.0,
    status: "Permanent",
    group: "Marketing",
    description:
      "dolor quis odio consequat varius integer ac leo pellentesque ultrices",
  },
  {
    username: "greinbeck1b",
    firstName: "Galvan",
    lastName: "Reinbeck",
    email: "greinbeck1b@example.com",
    birthDate: "1964-12-15",
    basicSalary: 17933052.14,
    status: "Contract",
    group: "Services",
    description: "proin interdum mauris non ligula pellentesque",
  },
  {
    username: "gbullivent1c",
    firstName: "Grady",
    lastName: "Bullivent",
    email: "gbullivent1c@example.com",
    birthDate: "1968-01-14",
    basicSalary: 32642211.11,
    status: "Contract",
    group: "Research and Development",
    description: "ut volutpat sapien arcu sed",
  },
  {
    username: "ckaming1d",
    firstName: "Currey",
    lastName: "Kaming",
    email: "ckaming1d@example.com",
    birthDate: "1968-01-23",
    basicSalary: 13767016.08,
    status: "Contract",
    group: "Legal",
    description: "justo aliquam quis turpis eget elit",
  },
  {
    username: "biorizzi1e",
    firstName: "Berke",
    lastName: "Iorizzi",
    email: "biorizzi1e@example.com",
    birthDate: "1975-08-06",
    basicSalary: 30648332.51,
    status: "Contract",
    group: "Support",
    description: "felis donec semper sapien a libero nam dui",
  },
  {
    username: "amarcone1f",
    firstName: "Andrea",
    lastName: "Marcone",
    email: "amarcone1f@example.com",
    birthDate: "1978-04-02",
    basicSalary: 15776352.44,
    status: "Contract",
    group: "Services",
    description:
      "in purus eu magna vulputate luctus cum sociis natoque penatibus",
  },
  {
    username: "ajugging1g",
    firstName: "Anneliese",
    lastName: "Jugging",
    email: "ajugging1g@example.com",
    birthDate: "1981-08-20",
    basicSalary: 37719363.89,
    status: "Permanent",
    group: "Accounting",
    description: "nec molestie sed justo pellentesque viverra pede",
  },
  {
    username: "lnavan1h",
    firstName: "Lucias",
    lastName: "Navan",
    email: "lnavan1h@example.com",
    birthDate: "1971-12-29",
    basicSalary: 24347693.73,
    status: "Contract",
    group: "Engineering",
    description: "sapien non mi integer ac neque duis bibendum morbi non",
  },
  {
    username: "onerne1i",
    firstName: "Oona",
    lastName: "Nerne",
    email: "onerne1i@example.com",
    birthDate: "1997-07-07",
    basicSalary: 35960698.57,
    status: "Permanent",
    group: "Business Development",
    description: "pellentesque volutpat dui maecenas tristique est et tempus",
  },
  {
    username: "sforder1j",
    firstName: "Shae",
    lastName: "Forder",
    email: "sforder1j@example.com",
    birthDate: "1996-07-13",
    basicSalary: 14223028.79,
    status: "Contract",
    group: "Sales",
    description: "sed tristique in tempus sit amet sem fusce consequat nulla",
  },
  {
    username: "rgeraud1k",
    firstName: "Reinhold",
    lastName: "Geraud",
    email: "rgeraud1k@example.com",
    birthDate: "1962-07-25",
    basicSalary: 13681120.2,
    status: "Contract",
    group: "Business Development",
    description: "lectus suspendisse potenti in eleifend quam a",
  },
  {
    username: "kcussins1l",
    firstName: "Katerina",
    lastName: "Cussins",
    email: "kcussins1l@example.com",
    birthDate: "1974-07-09",
    basicSalary: 37022206.75,
    status: "Permanent",
    group: "Services",
    description:
      "at nulla suspendisse potenti cras in purus eu magna vulputate",
  },
  {
    username: "jmansel1m",
    firstName: "Jordan",
    lastName: "Mansel",
    email: "jmansel1m@example.com",
    birthDate: "1989-05-02",
    basicSalary: 23135652.87,
    status: "Contract",
    group: "Sales",
    description: "cursus vestibulum proin eu mi nulla ac enim",
  },
  {
    username: "osprionghall1n",
    firstName: "Osgood",
    lastName: "Sprionghall",
    email: "osprionghall1n@example.com",
    birthDate: "1962-05-10",
    basicSalary: 7049823.58,
    status: "Contract",
    group: "Services",
    description: "congue vivamus metus arcu adipiscing molestie hendrerit",
  },
  {
    username: "scharte1o",
    firstName: "Sonnnie",
    lastName: "Charte",
    email: "scharte1o@example.com",
    birthDate: "1994-12-16",
    basicSalary: 6789186.0,
    status: "Permanent",
    group: "Human Resources",
    description: "est et tempus semper est quam pharetra",
  },
  {
    username: "bmacgorman1p",
    firstName: "Barthel",
    lastName: "MacGorman",
    email: "bmacgorman1p@example.com",
    birthDate: "1978-07-03",
    basicSalary: 16909486.68,
    status: "Contract",
    group: "Training",
    description: "eleifend quam a odio in hac habitasse",
  },
  {
    username: "aforestel1q",
    firstName: "Alden",
    lastName: "Forestel",
    email: "aforestel1q@example.com",
    birthDate: "1964-02-10",
    basicSalary: 26172544.74,
    status: "Contract",
    group: "Product Management",
    description:
      "nunc nisl duis bibendum felis sed interdum venenatis turpis enim",
  },
  {
    username: "qangless1r",
    firstName: "Quinlan",
    lastName: "Angless",
    email: "qangless1r@example.com",
    birthDate: "1991-07-10",
    basicSalary: 39062113.58,
    status: "Contract",
    group: "Business Development",
    description: "tortor risus dapibus augue vel accumsan tellus nisi",
  },
  {
    username: "lstaley1s",
    firstName: "Loree",
    lastName: "Staley",
    email: "lstaley1s@example.com",
    birthDate: "1998-07-19",
    basicSalary: 38851758.05,
    status: "Permanent",
    group: "Human Resources",
    description: "ultrices posuere cubilia curae mauris viverra",
  },
  {
    username: "glamyman1t",
    firstName: "Genevieve",
    lastName: "Lamyman",
    email: "glamyman1t@example.com",
    birthDate: "1997-02-09",
    basicSalary: 17052303.32,
    status: "Permanent",
    group: "Training",
    description: "libero convallis eget eleifend luctus ultricies eu nibh",
  },
  {
    username: "hhamer1u",
    firstName: "Hyacinthia",
    lastName: "Hamer",
    email: "hhamer1u@example.com",
    birthDate: "1977-03-25",
    basicSalary: 34546678.61,
    status: "Permanent",
    group: "Services",
    description: "pellentesque viverra pede ac diam",
  },
  {
    username: "mlochran1v",
    firstName: "Martita",
    lastName: "Lochran",
    email: "mlochran1v@example.com",
    birthDate: "1996-05-17",
    basicSalary: 12197362.99,
    status: "Permanent",
    group: "Services",
    description: "mi pede malesuada in imperdiet et",
  },
  {
    username: "rkimblen1w",
    firstName: "Rafael",
    lastName: "Kimblen",
    email: "rkimblen1w@example.com",
    birthDate: "1966-07-28",
    basicSalary: 9559559.0,
    status: "Contract",
    group: "Accounting",
    description: "magna at nunc commodo placerat praesent blandit",
  },
  {
    username: "bhartopp1x",
    firstName: "Berkley",
    lastName: "Hartopp",
    email: "bhartopp1x@example.com",
    birthDate: "1989-11-09",
    basicSalary: 11710902.95,
    status: "Contract",
    group: "Sales",
    description: "id consequat in consequat ut",
  },
  {
    username: "agurge1y",
    firstName: "Andre",
    lastName: "Gurge",
    email: "agurge1y@example.com",
    birthDate: "1982-12-12",
    basicSalary: 36282535.9,
    status: "Contract",
    group: "Human Resources",
    description: "mollis molestie lorem quisque ut",
  },
  {
    username: "stubbs1z",
    firstName: "Sheffy",
    lastName: "Tubbs",
    email: "stubbs1z@example.com",
    birthDate: "1978-08-29",
    basicSalary: 20183904.16,
    status: "Contract",
    group: "Support",
    description: "integer ac neque duis bibendum",
  },
  {
    username: "dsandercock20",
    firstName: "Demetria",
    lastName: "Sandercock",
    email: "dsandercock20@example.com",
    birthDate: "1999-05-25",
    basicSalary: 27927292.75,
    status: "Permanent",
    group: "Support",
    description: "aenean sit amet justo morbi ut odio cras mi pede",
  },
  {
    username: "njaggi21",
    firstName: "Nertie",
    lastName: "Jaggi",
    email: "njaggi21@example.com",
    birthDate: "1974-07-07",
    basicSalary: 37273001.33,
    status: "Permanent",
    group: "Human Resources",
    description: "congue etiam justo etiam pretium",
  },
  {
    username: "jzack22",
    firstName: "Jodi",
    lastName: "Zack",
    email: "jzack22@example.com",
    birthDate: "1999-08-21",
    basicSalary: 41803304.62,
    status: "Contract",
    group: "Training",
    description: "lectus vestibulum quam sapien varius ut blandit non interdum",
  },
  {
    username: "vungerecht23",
    firstName: "Verge",
    lastName: "Ungerecht",
    email: "vungerecht23@example.com",
    birthDate: "1971-07-23",
    basicSalary: 45671545.8,
    status: "Contract",
    group: "Accounting",
    description: "est donec odio justo sollicitudin",
  },
  {
    username: "vfley24",
    firstName: "Vance",
    lastName: "Fley",
    email: "vfley24@example.com",
    birthDate: "1980-12-10",
    basicSalary: 5678908.0,
    status: "Contract",
    group: "Support",
    description: "et ultrices posuere cubilia curae nulla",
  },
  {
    username: "apidgley25",
    firstName: "Alonso",
    lastName: "Pidgley",
    email: "apidgley25@example.com",
    birthDate: "1963-06-08",
    basicSalary: 45334335.47,
    status: "Contract",
    group: "Services",
    description: "nulla dapibus dolor vel est donec odio justo sollicitudin",
  },
  {
    username: "tmcgunley26",
    firstName: "Tine",
    lastName: "McGunley",
    email: "tmcgunley26@example.com",
    birthDate: "1983-08-13",
    basicSalary: 13429392.88,
    status: "Permanent",
    group: "Engineering",
    description:
      "purus aliquet at feugiat non pretium quis lectus suspendisse potenti",
  },
  {
    username: "bcoombes27",
    firstName: "Benson",
    lastName: "Coombes",
    email: "bcoombes27@example.com",
    birthDate: "1970-12-02",
    basicSalary: 42068686.55,
    status: "Contract",
    group: "Legal",
    description: "luctus et ultrices posuere cubilia curae donec pharetra",
  },
  {
    username: "asmallman28",
    firstName: "Audi",
    lastName: "Smallman",
    email: "asmallman28@example.com",
    birthDate: "1998-08-04",
    basicSalary: 28725627.69,
    status: "Permanent",
    group: "Sales",
    description: "molestie lorem quisque ut erat",
  },
  {
    username: "gheggman29",
    firstName: "Gregoire",
    lastName: "Heggman",
    email: "gheggman29@example.com",
    birthDate: "1996-12-17",
    basicSalary: 44052051.5,
    status: "Contract",
    group: "Engineering",
    description:
      "varius nulla facilisi cras non velit nec nisi vulputate nonummy",
  },
  {
    username: "cvongrollmann2a",
    firstName: "Cly",
    lastName: "von Grollmann",
    email: "cvongrollmann2a@example.com",
    birthDate: "1966-09-07",
    basicSalary: 27741411.52,
    status: "Contract",
    group: "Accounting",
    description: "luctus et ultrices posuere cubilia curae duis",
  },
  {
    username: "bmarien2b",
    firstName: "Berry",
    lastName: "Marien",
    email: "bmarien2b@example.com",
    birthDate: "1993-10-17",
    basicSalary: 42098349.78,
    status: "Permanent",
    group: "Legal",
    description: "non velit nec nisi vulputate",
  },
  {
    username: "gtows2c",
    firstName: "Graham",
    lastName: "Tows",
    email: "gtows2c@example.com",
    birthDate: "1994-06-19",
    basicSalary: 43272088.14,
    status: "Contract",
    group: "Marketing",
    description: "mollis molestie lorem quisque ut erat curabitur gravida",
  },
  {
    username: "ppignon2d",
    firstName: "Philip",
    lastName: "Pignon",
    email: "ppignon2d@example.com",
    birthDate: "1982-05-22",
    basicSalary: 28799853.8,
    status: "Contract",
    group: "Accounting",
    description: "et eros vestibulum ac est lacinia nisi venenatis tristique",
  },
  {
    username: "vbanaszewski2e",
    firstName: "Vladimir",
    lastName: "Banaszewski",
    email: "vbanaszewski2e@example.com",
    birthDate: "1985-03-11",
    basicSalary: 15019031.44,
    status: "Contract",
    group: "Sales",
    description: "donec odio justo sollicitudin ut suscipit a feugiat",
  },
  {
    username: "dmcilwraith2f",
    firstName: "Dannye",
    lastName: "McIlwraith",
    email: "dmcilwraith2f@example.com",
    birthDate: "1979-06-13",
    basicSalary: 18884682.17,
    status: "Permanent",
    group: "Product Management",
    description: "odio in hac habitasse platea dictumst maecenas ut",
  },
  {
    username: "gdowers2g",
    firstName: "Gavra",
    lastName: "Dowers",
    email: "gdowers2g@example.com",
    birthDate: "1983-05-03",
    basicSalary: 42623864.81,
    status: "Permanent",
    group: "Accounting",
    description: "ipsum aliquam non mauris morbi",
  },
  {
    username: "mbreazeall2h",
    firstName: "Marion",
    lastName: "Breazeall",
    email: "mbreazeall2h@example.com",
    birthDate: "1969-07-09",
    basicSalary: 9170573.0,
    status: "Permanent",
    group: "Accounting",
    description: "sem praesent id massa id nisl venenatis lacinia",
  },
  {
    username: "sbarles2i",
    firstName: "Sib",
    lastName: "Barles",
    email: "sbarles2i@example.com",
    birthDate: "1968-08-22",
    basicSalary: 12147612.91,
    status: "Permanent",
    group: "Legal",
    description: "libero convallis eget eleifend luctus ultricies eu",
  },
  {
    username: "askyppe2j",
    firstName: "Ardelis",
    lastName: "Skyppe",
    email: "askyppe2j@example.com",
    birthDate: "1994-04-21",
    basicSalary: 47674341.96,
    status: "Permanent",
    group: "Sales",
    description: "praesent blandit nam nulla integer pede justo lacinia",
  },
  {
    username: "yduckerin2k",
    firstName: "Yolanda",
    lastName: "Duckerin",
    email: "yduckerin2k@example.com",
    birthDate: "1998-05-14",
    basicSalary: 31133412.7,
    status: "Permanent",
    group: "Engineering",
    description: "nam nulla integer pede justo lacinia eget",
  },
  {
    username: "dauchinleck2l",
    firstName: "Daryl",
    lastName: "Auchinleck",
    email: "dauchinleck2l@example.com",
    birthDate: "1987-01-17",
    basicSalary: 46844573.64,
    status: "Permanent",
    group: "Sales",
    description:
      "imperdiet et commodo vulputate justo in blandit ultrices enim",
  },
  {
    username: "ailyasov2m",
    firstName: "Adolphus",
    lastName: "Ilyasov",
    email: "ailyasov2m@example.com",
    birthDate: "1986-09-02",
    basicSalary: 36947544.62,
    status: "Contract",
    group: "Human Resources",
    description: "eleifend donec ut dolor morbi vel lectus",
  },
  {
    username: "sguion2n",
    firstName: "Stesha",
    lastName: "Guion",
    email: "sguion2n@example.com",
    birthDate: "1965-09-23",
    basicSalary: 11084344.49,
    status: "Permanent",
    group: "Marketing",
    description:
      "diam erat fermentum justo nec condimentum neque sapien placerat ante",
  },
  {
    username: "apenner2o",
    firstName: "Audy",
    lastName: "Penner",
    email: "apenner2o@example.com",
    birthDate: "1977-07-17",
    basicSalary: 18463427.84,
    status: "Permanent",
    group: "Sales",
    description:
      "maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices",
  },
  {
    username: "tgrahame2p",
    firstName: "Tucker",
    lastName: "Grahame",
    email: "tgrahame2p@example.com",
    birthDate: "1988-04-12",
    basicSalary: 26618987.84,
    status: "Contract",
    group: "Services",
    description:
      "accumsan felis ut at dolor quis odio consequat varius integer",
  },
  {
    username: "lkerbler2q",
    firstName: "Lulu",
    lastName: "Kerbler",
    email: "lkerbler2q@example.com",
    birthDate: "1984-07-11",
    basicSalary: 13116014.51,
    status: "Permanent",
    group: "Services",
    description: "velit donec diam neque vestibulum eget vulputate ut",
  },
  {
    username: "cbruna2r",
    firstName: "Courtnay",
    lastName: "Bruna",
    email: "cbruna2r@example.com",
    birthDate: "1973-02-14",
    basicSalary: 22352348.68,
    status: "Permanent",
    group: "Services",
    description: "dui proin leo odio porttitor id consequat in consequat ut",
  },
];
